### ISSUE TITLE
Use JsonConverter converters?

### ISSUE THREAD

**Issue by tgrushka** [atreeon/morphy#2]
I was interested in this package until I discovered that the use of JsonConverter classes/annotations on custom fields does not work. JsonSerializable requires specifying converters for fields that have types that are not built into json_serializable. For example, using a type like UuidValue in a field, I'd like to convert it to/from String.

I can do this with freezed, but freezed also does not allow specifying this globally for types or on classes (one has to add the converter to every field). Would give your package an advantage to be able to specify custom converters at the class level and also in build.yaml (which neither freezed nor json_serializable offers).

Example:
```dart

class UuidValueConverter extends JsonConverter<UuidValue, String> {
  const UuidValueConverter();

  @override
  UuidValue fromJson(String json) => UuidValue.fromString(json);

  @override
  String toJson(UuidValue object) => object.uuid;
}

@Morphy(converters: [UuidValueConverter()])
abstract class $Pet {
  UuidValue? get id;
  String get name;
}
```

or build.yaml:
```yaml
targets:
  $default:
    builders:
      morphy:
        options:
          converters:
            - UuidValueConverter
```
